# Generated by Django 3.2.7 on 2021-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
        ('eshop_products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.ProductCategory'),
        ),
    ]
